# Generated by Django 4.1 on 2022-08-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_playlist_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_link',
        ),
        migrations.AddField(
            model_name='song',
            name='song_url',
            field=models.URLField(default=''),
        ),
    ]
